<img src="http://2.bp.blogspot.com/-H2m-BFydExw/Wkc9gJQE8GI/AAAAAAAAcZI/pJhLUIEj9zMe2fmVsQuK2UWFbrVagaongCK4BGAYYCw/s0/%25E6%2588%2590%25E5%258A%259F%25E9%2581%258E%25E7%25A8%258B.png"
style="width:100px;height:100px;float:left"><br/><br/><br/><br/><br/>  
### 專案名稱: python測試  
### 功能描述: 資料結構測試
### 版權所有: Dunk  
### 程式撰寫: Dunk  
### 參考網址: https://www.runoob.com/python3/python3-data-structure.html
### 撰寫日期：2020/02/18
### 改版日期:  
### 改版備註:  

列表
Python中列表是可变的，这是它区别于字符串和元组的最重要的特点，一句话概括即：列表可以修改，而字符串和元组不能。
以下是 Python 中列表的方法：
<table class="reference">
<tr>
<th>方法</th>
<th>描述</th>
</tr>
<tr>
<td>list.append(x)
</td>
<td>把一个元素添加到列表的结尾，相当于 a[len(a):] = [x]。
</td>
</tr>

<tr>
<td>list.extend(L)
</td>
<td>通过添加指定列表的所有元素来扩充列表，相当于 a[len(a):] = L。 
</td>
</tr>

<tr>
<td>list.insert(i, x)
</td>
<td>在指定位置插入一个元素。第一个参数是准备插入到其前面的那个元素的索引，例如 a.insert(0, x) 会插入到整个列表之前，而 a.insert(len(a), x) 相当于 a.append(x) 。
</td>
</tr>
<tr>
<td>list.remove(x)
</td>
<td>删除列表中值为 x 的第一个元素。如果没有这样的元素，就会返回一个错误。
</td>
</tr>

<tr>
<td>list.pop([i])
</td>
<td>从列表的指定位置移除元素，并将其返回。如果没有指定索引，a.pop()返回最后一个元素。元素随即从列表中被移除。（方法中 i 两边的方括号表示这个参数是可选的，而不是要求你输入一对方括号，你会经常在 Python 库参考手册中遇到这样的标记。）
</td>
</tr>

<tr>
<td>list.clear()
</td>
<td>移除列表中的所有项，等于del a[:]。
</td>
</tr>

<tr>
<td>list.index(x)
</td>
<td>返回列表中第一个值为 x 的元素的索引。如果没有匹配的元素就会返回一个错误。
</td>
</tr>

<tr>
<td>list.count(x)
</td>
<td>返回 x 在列表中出现的次数。
</td>
</tr>

<tr>
<td>list.sort()
</td>
<td>对列表中的元素进行排序。
</td>
</tr>

<tr>
<td>list.reverse()
</td>
<td>倒排列表中的元素。
</td>
</tr>

<tr>
<td>list.copy()
</td>
<td>返回列表的浅复制，等于a[:]。
</td>
</tr>
</table>

In [15]:
'''測試list'''
a = [1,2,3,4,5,6]
a.append(7)
print(a)
a.extend([99,88,77])
print(a)
a.insert(0,100)
print(a)
print(a.index(99))
a.remove(99)
print(a)
a.reverse()
print(a)
a.sort()
print(a)
a.reverse()
print(a)
#淺複製(不會修改到參考物件)
b = a.copy()
b[0] = -1
print(b)
print(a)

[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7, 99, 88, 77]
[100, 1, 2, 3, 4, 5, 6, 7, 99, 88, 77]
8
[100, 1, 2, 3, 4, 5, 6, 7, 88, 77]
[77, 88, 7, 6, 5, 4, 3, 2, 1, 100]
[1, 2, 3, 4, 5, 6, 7, 77, 88, 100]
[100, 88, 77, 7, 6, 5, 4, 3, 2, 1]
[-1, 88, 77, 7, 6, 5, 4, 3, 2, 1]
[100, 88, 77, 7, 6, 5, 4, 3, 2, 1]


In [18]:
'''使用堆疊'''
from collections import deque
queue = deque(["Eric", "John", "Michael"])
# Terry arrives
queue.append("Terry")
# Graham arrives
queue.append("Graham")
# The first to arrive now leaves
print(queue.popleft())
# The second to arrive now leaves
print(queue.popleft())
# Remaining queue in order of arrival
print(queue)

Eric
John
deque(['Michael', 'Terry', 'Graham'])


In [28]:
# 列表推导式
# 列表推导式提供了从序列创建列表的简单途径。通常应用程序将一些操作应用于某个序列的每个元素，用其获得的结果作为生成新列表的元素，
# 或者根据确定的判定条件创建子序列。
# 每个列表推导式都在 for 之后跟一个表达式，然后有零到多个 for 或 if 子句。返回结果是一个根据表达从其后的 for 和 if 上下文环境
# 中生成出来的列表。如果希望表达式推导出一个元组，就必须使用括号。
import numpy as np
test_list = [ [x,x**2] for x in np.arange(10)]
print(test_list)
#加入條件
test_list_odd = [x for x in test_list if x[0]%2==1]
print(test_list_odd)
test_list_even = [x for x in test_list if x[0]%2==0]
print(test_list_even)

#套用兩個
vec1 = [2, 4, 6]
vec2 = [4, 3, -9]
print([x*y for x in vec1 for y in vec2])
print([x+y for x in vec1 for y in vec2])
print([vec1[i]*vec2[i] for i in range(len(vec1))])

[[0, 0], [1, 1], [2, 4], [3, 9], [4, 16], [5, 25], [6, 36], [7, 49], [8, 64], [9, 81]]
[[1, 1], [3, 9], [5, 25], [7, 49], [9, 81]]
[[0, 0], [2, 4], [4, 16], [6, 36], [8, 64]]
[8, 6, -18, 16, 12, -36, 24, 18, -54]
[6, 5, -7, 8, 7, -5, 10, 9, -3]
[8, 12, -54]


In [12]:
# 嵌套列表解析
# Python的列表还可以嵌套。
import numpy as np
test_array = np.random.RandomState(42).randint(10,size=(3,3))
print(test_array)
#轉成一維
print([row[i] for row in test_array for i in range(len(row))])
#del
a = [-1, 1, 66.25, 333, 333, 1234.5]
del a[0]
print(a)
del a[2:4]
print(a)
del a[:]
print(a)

[[6 3 7]
 [4 6 9]
 [2 6 7]]
[6, 3, 7, 4, 6, 9, 2, 6, 7]
[1, 66.25, 333, 333, 1234.5]
[1, 66.25, 1234.5]
[]


In [13]:
'''元组和序列'''
t = 12345, 54321, 'hello!'
print(t[0])
print(t)
# Tuples may be nested:
u = t, (1, 2, 3, 4, 5)
print(u)

12345
(12345, 54321, 'hello!')
((12345, 54321, 'hello!'), (1, 2, 3, 4, 5))


In [19]:
'''集合'''
# 以下演示了两个集合的操作

a = set('abracadabra')
b = set('alacazam')
#a中唯一的字母
print(a)
#b中唯一的字母
print(b)
# 在 a 中的字母，但不在 b 中
print(a - b)
# 在 a 或 b 中的字母
print(a | b)
# 在 a 和 b 中都有的字母
print(a & b)
# 在 a 或 b 中的字母，但不同时在 a 和 b 中
print(a ^ b)

{'c', 'b', 'r', 'd', 'a'}
{'c', 'z', 'm', 'l', 'a'}
{'b', 'r', 'd'}
{'r', 'z', 'd', 'c', 'm', 'l', 'b', 'a'}
{'c', 'a'}
{'r', 'z', 'd', 'm', 'l', 'b'}


In [28]:
'''字典'''
tel = {'jack': 4098, 'sape': 4139}
print(tel.keys())
print(tel.values())
print(tel.items())
for k,v in tel.items():
    print('key:{0}\tvalue:{1}'.format(k,v))
#直接建構
print(dict([('sape', 4139), ('guido', 4127), ('jack', 4098)]))
print(dict(sape=4139, guido=4127, jack=4098))

dict_keys(['jack', 'sape'])
dict_values([4098, 4139])
dict_items([('jack', 4098), ('sape', 4139)])
key:jack	value:4098
key:sape	value:4139
{'jack': 4098, 'guido': 4127, 'sape': 4139}
{'jack': 4098, 'guido': 4127, 'sape': 4139}


In [33]:
'''遍立'''
knights = {'gallahad': 'the pure', 'robin': 'the brave'}
for k, v in knights.items():
    print(k, v)
#同时遍历两个或更多的序列，可以使用 zip() 组合：
questions = ['name', 'quest', 'favorite color']
answers = ['lancelot', 'the holy grail', 'blue']
reindex = [3,4,6]
for q, a,i in zip(questions, answers,reindex):
    print('What is your {0}?  It is {1}. and index is {2}'.format(q, a, i))
    
# 要反向遍历一个序列，首先指定这个序列，然后调用 reversed() 函数：    
for i in reversed(range(1, 10, 2)):
    print(i)

#要按顺序遍历一个序列，使用 sorted() 函数返回一个已排序的序列，并不修改原值：    
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']
for f in sorted(set(basket)):
    print(f)    

gallahad the pure
robin the brave
What is your name?  It is lancelot. and index is 3
What is your quest?  It is the holy grail. and index is 4
What is your favorite color?  It is blue. and index is 6
9
7
5
3
1
apple
banana
orange
pear
