### 專案名稱: 資料導向程式設計練習
### 功能描述:  測試python指令
### 版權所有: Dunk  
### 程式撰寫: Dunk  
### 撰寫日期：2020/11/10
### 改版日期:  
### 改版備註:  

In [7]:
x = [1,3,6,8]
print(x)
print(type(x))
x[1] = "peekabo"
print(x)
# 將元素新增在末端
x.append("adff")
print(x)
# 指定位置塞入元素
x.insert(1,"safari")
print(x)
# 指定位置移除元素
x.pop(2)
print(x)
print("safari" in x)

[1, 3, 6, 8]
<class 'list'>
[1, 'peekabo', 6, 8]
[1, 'peekabo', 6, 8, 'adff']
[1, 'safari', 'peekabo', 6, 8, 'adff']
[1, 'safari', 6, 8, 'adff']
True


In [14]:
# 排序
a = [7,2,5,1,3]
print(sorted(a))
print(sorted(a,reverse=True))

# 依照字串長度升幕排序
b =['saw','small','he','foxes','six']
print(sorted(b,key=len))

[1, 2, 3, 5, 7]
[7, 5, 3, 2, 1]
['he', 'saw', 'six', 'small', 'foxes']


In [17]:
# tuple
nested_tup = (4,5,6),(7,8)
print(nested_tup)

#解構值組
tup = (4,5,6)
a,b,c = tup
print(c)

#變數交換
x,y = 1,2
x,y = y,x
print(x)
print(y)

((4, 5, 6), (7, 8))
6
2
1


In [26]:
# 字典
d1 = {'a':'some value','b':[1,2,3,4]}
print(d1)
# 新增元素
d1['c'] = 'baby'
print(d1)
# 取值
print(d1['b'])
print(d1.get('z','there is no key'))

#刪除元素
d1.pop('b')
print(d1)
print(d1.pop('z','there is no key'))
#取物件
print(d1.items())

{'a': 'some value', 'b': [1, 2, 3, 4]}
{'a': 'some value', 'b': [1, 2, 3, 4], 'c': 'baby'}
[1, 2, 3, 4]
there is no key
{'a': 'some value', 'c': 'baby'}
there is no key
dict_items([('a', 'some value'), ('c', 'baby')])


In [29]:
# 更新字典
a = {'a':1,'b':2}
b = {'b':0,'c':3}
a.update(b)
print(a)
# key value 合併轉成字典
tmp = dict(zip(['name','age'],['Tommy',20]))
print(tmp)

{'a': 1, 'b': 0, 'c': 3}
{'name': 'Tommy', 'age': 20}


In [31]:
# 集合
a = set([2,2,2,1,3,3])
print(a)
a ={2,2,2,1,3,3}
print(a)

{1, 2, 3}
{1, 2, 3}


In [33]:
#DataFrame
import pandas as pd
df = pd.read_csv("NBApoints.csv")

In [36]:
print(df.shape)
print(dir(df))

(476, 30)
['AST', 'Age', 'BLK', 'DRB', 'FG', 'FGA', 'FT', 'FTA', 'G', 'GS', 'MP', 'ORB', 'PF', 'Player', 'Pos', 'Rk', 'STL', 'T', 'TOV', 'TRB', 'Tm', '_AXIS_ALIASES', '_AXIS_IALIASES', '_AXIS_LEN', '_AXIS_NAMES', '_AXIS_NUMBERS', '_AXIS_ORDERS', '_AXIS_REVERSED', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__

In [19]:
import pandas as pd
df = pd.DataFrame([['green','M',10.1,'class1'],['red','L',13.2,'class2'],['blue','XL',15.3,'class1']])
df.columns=['color','size','price','classlabel']
print(df)
# 定義規則字典
size_mapping = {'XL':3,'L':2,'M':1}
# 手作類型標籤編碼
df['size'] = df['size'].map(size_mapping)
print(df)
# 使用sklearn編碼
from sklearn.preprocessing import LabelEncoder
label_coder = LabelEncoder()
y = label_coder.fit_transform(df['classlabel'])
print(y)
# 逆轉換回原值
print(label_coder.inverse_transform(y))
print(y.reshape(-1,1))

X = df[['color','size','price']].values
print(X)
color_le = LabelEncoder()
X[:,0] = color_le.fit_transform(X[:,0])
print(X)

#獨熱編碼
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer 
# The last arg ([0]) is the list of columns you want to transform in this step
# 只獨熱編碼第一欄
ct = ColumnTransformer([("Name_Of_Your_Step", OneHotEncoder(),[0])], remainder="passthrough") 
print(ct.fit_transform(X))
ohe = OneHotEncoder()
# 獨熱編碼所有欄
print(ohe.fit_transform(X).toarray())

   color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.2     class2
2   blue   XL   15.3     class1
   color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.2     class2
2   blue     3   15.3     class1
[0 1 0]
['class1' 'class2' 'class1']
[[0]
 [1]
 [0]]
[['green' 1 10.1]
 ['red' 2 13.2]
 ['blue' 3 15.3]]
[[1 1 10.1]
 [2 2 13.2]
 [0 3 15.3]]
[[0.0 1.0 0.0 1 10.1]
 [0.0 0.0 1.0 2 13.2]
 [1.0 0.0 0.0 3 15.3]]
[[0. 1. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 1.]]


In [24]:
import pandas as pd
import numpy as np
a = pd.Series(np.arange(10))
print(a)
#函式apply
print(a.apply(lambda x:x+4))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32
0     4
1     5
2     6
3     7
4     8
5     9
6    10
7    11
8    12
9    13
dtype: int64
