### 專案名稱:  TQC+ 網頁資料擷取與分析
### 功能描述:  第3類：資料分析能力
### 版權所有: Dunk  
### 程式撰寫: Dunk  
### 撰寫日期：2020/07/29
### 改版日期:  
### 改版備註:  

#### TQC+ 網頁資料擷取與分析 301 學生成績
1. 題目說明:
請開啟PYD03.py檔案，依下列題意進行作答，使輸出值符合題意要求。作答完成請另存新檔為PYA03.py再進行評分。

2. 設計說明：
利用程式內提供的數據，依下列要求進行輸出：

輸出全部學生的成績，行標題設為科目的名稱；列標題為每個人的名字
輸出後二位學生的所有成績
將自然成績做遞減排序輸出
僅列小黃的成績，並將其英文成績改為80
3. 輸入輸出：
輸入說明
無

輸出說明
輸出全部學生的成績，行標題設為科目的名稱；列標題為每個人的名字
輸出後二位學生的所有成績
將自然成績做遞減排序輸出
僅列小黃的成績，並將其英文成績改為80

In [1]:
# -*- coding: utf-8 -*-
# 載入 pandas 模組縮寫為 pd
import pandas as pd

# 資料輸入
datas = [[75, 62, 85, 73, 60], [91, 53, 56, 63, 65],
         [71, 88, 51, 69, 87], [69, 53, 87, 74, 70]]
indexs = ["小林", "小黃", "小陳", "小美"]
columns = ["國語", "數學", "英文", "自然", "社會"]
df = pd.DataFrame(datas, columns=columns,  index=indexs)

print('行標題為科目，列題標為個人的所有學生成績')
print(df)
print()

# 輸出後二位學生的所有成績
print('後二位的成績')
print(df[-2:])
print()

# 將自然成績做遞減排序輸出
df1 = df.sort_values(by="自然", ascending=False)
print('以自然遞減排序')
print(df1['自然'])
print()

# 僅列小黃的成績，並將其英文成績改為80
df.loc["小黃", "英文"] = 80
print('小黃的成績')
# 注意寫法
print(df.T.小黃)


行標題為科目，列題標為個人的所有學生成績
    國語  數學  英文  自然  社會
小林  75  62  85  73  60
小黃  91  53  56  63  65
小陳  71  88  51  69  87
小美  69  53  87  74  70

後二位的成績
    國語  數學  英文  自然  社會
小陳  71  88  51  69  87
小美  69  53  87  74  70

以自然遞減排序
小美    74
小林    73
小陳    69
小黃    63
Name: 自然, dtype: int64

小黃的成績
國語    91
數學    53
英文    80
自然    63
社會    65
Name: 小黃, dtype: int64


#### TQC+ 網頁資料擷取與分析 302 矩陣
1. 題目說明:
請開啟PYD03.py檔案，依下列題意進行作答，使輸出值符合題意要求。作答完成請另存新檔為PYA03.py再進行評分。

2. 設計說明：
請用numpy隨機產生5~15之間，15個正整數並輸出
請將 1. 轉成3×5的X矩陣並輸出
請輸出X矩陣的最大值
請輸出X矩陣的最小值
請輸出X矩陣的總和
請輸出X矩陣四個角落的元素內容
3. 輸入輸出：
輸入說明
無

輸出說明
請用numpy隨機產生5~15之間，15個正整數並輸出
請將 1. 轉成3×5的X矩陣並輸出
請輸出X矩陣的最大值
請輸出X矩陣的最小值
請輸出X矩陣的總和
請輸出X矩陣四個角落的元素內容

In [2]:
# --開始--批改評分使用，請勿變動
set_seed = 123
# --結束--批改評分使用，請勿變動

import numpy as np

x = np.random.RandomState(set_seed).randint(low=5, high=16, size=15)
print('隨機正整數：', x)

x = x.reshape(3, 5)
print('X矩陣內容：')
print(x)
print('最大：', np.max(x))
print('最小：', np.min(x))
print('總和：', np.sum(x))
print('四個角落元素：')
print(x[np.ix_([0,2], [0,4])])


隨機正整數： [ 7  7 11  6  8 15 14 11  6  5  6 14  5  5 14]
X矩陣內容：
[[ 7  7 11  6  8]
 [15 14 11  6  5]
 [ 6 14  5  5 14]]
最大： 15
最小： 5
總和： 134
四個角落元素：
[[ 7  8]
 [ 6 14]]


#### TQC+ 網頁資料擷取與分析 303 果菜批發市場拍賣行情
1. 題目說明:
請開啟PYD03.py檔案，依下列題意進行作答，使輸出值符合題意要求。作答完成請另存新檔為PYA03.py再進行評分。

2. 設計說明：
某日各果菜批發市場之西瓜與香瓜之拍賣行情價量表如下：
西瓜價	西瓜量	香瓜價	香瓜量
三重區	9	203674	13.2	18894
台中市	11.7	180785	12.3	54894
台北一	10.1	127802	14.7	18563
台北二	11.8	28604	14.9	21963
台東市	13.2	600	13.1	900
板橋區	6.9	38071	9.6	3555
高雄市	12.1	35660	10.6	9005
嘉義市	12	15000	13	12000
鳳山區	11.7	48770	9.1	14370
豐原區	9.84	6100	11.89	8980
上述的資料已在PYD03.py中，請撰寫一程式建立資料結構，其中直行標題為項目（西瓜價、西瓜量、香瓜價、香瓜價），橫列標題為交易市場；接著完成下列項目：
a. 輸出如拍賣行情價量表
b. 以西瓜價遞減排序後，輸出各市場的西瓜價
c. 計算台北一市場西瓜/香瓜價量的行情並輸出
d. 將「三重市」改為「三重區」、「香瓜價」改為「洋香瓜價」、「香瓜量」改為「洋香瓜量」，重新輸出整個表格

In [3]:
# 載入 pandas 模組縮寫為 pd
import pandas as pd

#　建構資料
data = [[9, 203674, 13.2, 18894],
       [11.7, 180785, 12.3, 54894],
       [10.1, 127802, 14.7, 18563],
       [11.8, 28604, 14.9, 21963],
       [13.2, 600, 13.1, 900],
       [6.9, 38071, 9.6, 3555],
       [12.1, 35660, 10.6, 9005],
       [12, 15000, 13, 12000],
       [11.7, 48770, 9.1, 14370],
       [9.84, 6100, 11.89, 8980]]
indexs = ["三重市", "台中市", "台北一", "台北二", "台東市", "板橋區", "高雄市", "嘉義市", "鳳山區", "豐原區"]
columns = ["西瓜價", "西瓜量", "香瓜價", "香瓜量"]

df = pd.DataFrame(data, columns=columns,  index=indexs)
print('西瓜與香瓜之拍賣行情價量表')
print(df)
print()  # 使用print分隔


df1 = df.sort_values(by="西瓜價", ascending=False)
print('以西瓜價遞減排序')
print(df1['西瓜價'])
print()  # 使用print分隔

# 計算台北一市場西瓜/香瓜價量的行情並輸出
df.T["台北一"]
print('台北一市場的行情')
print(df.T["台北一"])
print()  # 使用print分隔

indexs[0] = "三重區"
#注意要槓掉
#df.index = ____
columns[2] = "洋香瓜價"
columns[3] = "洋香瓜量"
#注意要槓掉
#df.____ = ____
df = pd.DataFrame(data, columns=columns,  index=indexs)
print('全體市場行情')
print(df)


西瓜與香瓜之拍賣行情價量表
       西瓜價     西瓜量    香瓜價    香瓜量
三重市   9.00  203674  13.20  18894
台中市  11.70  180785  12.30  54894
台北一  10.10  127802  14.70  18563
台北二  11.80   28604  14.90  21963
台東市  13.20     600  13.10    900
板橋區   6.90   38071   9.60   3555
高雄市  12.10   35660  10.60   9005
嘉義市  12.00   15000  13.00  12000
鳳山區  11.70   48770   9.10  14370
豐原區   9.84    6100  11.89   8980

以西瓜價遞減排序
台東市    13.20
高雄市    12.10
嘉義市    12.00
台北二    11.80
台中市    11.70
鳳山區    11.70
台北一    10.10
豐原區     9.84
三重市     9.00
板橋區     6.90
Name: 西瓜價, dtype: float64

台北一市場的行情
西瓜價        10.1
西瓜量    127802.0
香瓜價        14.7
香瓜量     18563.0
Name: 台北一, dtype: float64

全體市場行情
       西瓜價     西瓜量   洋香瓜價   洋香瓜量
三重區   9.00  203674  13.20  18894
台中市  11.70  180785  12.30  54894
台北一  10.10  127802  14.70  18563
台北二  11.80   28604  14.90  21963
台東市  13.20     600  13.10    900
板橋區   6.90   38071   9.60   3555
高雄市  12.10   35660  10.60   9005
嘉義市  12.00   15000  13.00  12000
鳳山區  11.70   48770   9.10  14370
豐原區   9.84    6100 

#### TQC+ 網頁資料擷取與分析 304 資料處理與分析
1. 題目說明：
請開啟PYD03.py檔案，依下列題意進行作答，使輸出值符合題意要求。作答完成請另存新檔為PYA03.py再進行評分。

2. 設計說明：
請讀取read.csv中的資料轉換成numpy陣列，並輸出以下資訊：

資料集型態
平均數
中位數
標準差
變異數
極差值
註：數值需四捨五入至小數點後兩位

3. 輸入輸出：
輸入說明
讀取read.csv的內容

輸出說明
資料集型態
平均數
中位數
標準差
變異數
極差值
輸入輸出範例
範例輸入
無

範例輸出
Alt text

In [4]:
# 載入 numpy 模組
import numpy as np
# 載入 pandas 模組
import pandas as pd

# 讀入 read.csv 檔案
np_array = np.array(pd.read_csv("read.csv").values)

# 判斷資料型態
print('資料型態：%s' % type(np_array))
# 計算平均數
print('平均值：%.2f' % np.mean(np_array))
# 計算中位數
print('中位數：%.2f' % np.median(np_array))
# 計算標準差
print('標準差：%.2f' % np.std(np_array))
# 計算變異數
print('變異數：%.2f' % np.var(np_array))
# 計算極差值
# 注意要先暫存
result = np.max(np_array) - np.min(np_array)
print('極差值：%.2f' % result)


資料型態：<class 'numpy.ndarray'>
平均值：50.48
中位數：53.00
標準差：27.57
變異數：760.27
極差值：94.00


#### TQC+ 網頁資料擷取與分析 305 登革熱病例統計
1. 題目說明:
請開啟PYD03.py檔案，依下列題意進行作答，使輸出值符合題意要求。作答完成請另存新檔為PYA03.py再進行評分。

2. 設計說明：
請撰寫一程式，讀取登革熱近12個月每日確定病例統計read.csv，接著依序輸出下列項目：
a. 以遞減順序顯示居住縣市的病例人數
b. 顯示感染病例人數最多的5個國家，並按遞減順序顯示
c. 顯示台北市各區病例人數
d. 顯示台北市最近病例的日期

3. 輸入輸出：
輸入說明
讀取read.csv

輸出說明
分別輸出下列四段資料：
a. 以遞減順序顯示居住縣市的病例人數
b. 顯示感染病例人數最多的5個國家，並按遞減順序顯示
c. 顯示台北市各區病例人數
d. 顯示台北市最近病例的日期

In [5]:
# 載入 pandas 模組縮寫為 pd
import pandas as pd

# 讀取csv檔
df1 = pd.read_csv("read.csv", encoding="utf-8", sep=",", header=0)

# 注意要用count
# 居住縣市病例人數，並按遞減順序顯示
df_county = df1.groupby("居住縣市")["居住縣市"].count()
print(df_county.sort_values(ascending=False))
# 顯示感染病例人數最多的5個國家，並按遞減順序顯示
df_country = df1.groupby("感染國家")["感染國家"].count()
print(df_country.sort_values(ascending=False).head(5))
# 台北市各區病例人數
df_taipei = df1[df1.居住縣市 == "台北市"]
print(df_taipei.groupby("居住鄉鎮")["居住鄉鎮"].count())
# 台北市最近病例的日期
print("發病日: " + df_taipei.發病日.max())


居住縣市
台北市    76
新北市    60
台中市    43
桃園市    43
高雄市    42
台南市    20
彰化縣    14
新竹市     8
屏東縣     7
南投縣     6
新竹縣     5
苗栗縣     5
嘉義縣     4
雲林縣     3
宜蘭縣     2
基隆市     2
台東縣     2
澎湖縣     2
嘉義市     1
Name: 居住縣市, dtype: int64
感染國家
越南      94
菲律賓     50
泰國      44
馬來西亞    33
緬甸      29
Name: 感染國家, dtype: int64
居住鄉鎮
中山區     8
中正區    10
信義區     7
內湖區    10
北投區     1
南港區     7
士林區     7
大同區     5
大安區    10
文山區     2
松山區     3
萬華區     6
Name: 居住鄉鎮, dtype: int64
發病日: 2018/06/25
