### 專案名稱: PythonForFinanace書籍練習
### 功能描述: chap1測試
### 版權所有: Dunk  
### 程式撰寫: Dunk  
### 撰寫日期：2020/03/11
### 改版日期:  
### 改版備註: 2020/03/12 繼續練習

In [70]:
# 查詢內建函式
dir('__builtin__')

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


#### The formula used is given here:
#### $FV = PV(1+R)^{n}...(1)$
- FV is the future value
- PV is the present value
- R is the period deposit rate while n is the number of periods.

In [71]:
# 撰寫函式
def fv_f(fv,r,n):
    """
    Objective: estimate present value
                     fv
    formula  : pv=-------------
                   (1+r)^n
          fv: fture value
          r : discount periodic rate
    n : number of periods

    Example #1  >>>pv_f(100,0.1,1)
                   90.9090909090909
    
    Example #2: >>>pv_f(r=0.1,fv=100,n=1)
                    90.9090909090909
    """
    return fv/(1+r)**n

In [72]:
# 測試函式
print(fv_f(100,0.02,20))
print(fv_f(100,0.1,2))

67.29713331080575
82.64462809917354


In [73]:
#查詢函式定義
help(fv_f)
?fv_f
??fv_f

Help on function fv_f in module __main__:

fv_f(fv, r, n)
    Objective: estimate present value
                     fv
    formula  : pv=-------------
                   (1+r)^n
          fv: fture value
          r : discount periodic rate
    n : number of periods
    
    Example #1  >>>pv_f(100,0.1,1)
                   90.9090909090909
    
    Example #2: >>>pv_f(r=0.1,fv=100,n=1)
                    90.9090909090909



### Net Present Value (NPV)
#### $PV=$$\frac{FV}{(1+R)^n}...(2)$
- PV is the present value
- FV is the future value
- R is the period discount rate
- n is the number of periods.

>此方法的理論是將投資的未來現金流量，全部折現成投資始日的價值，稱為該投資的淨現金流量，或稱為淨現值（NPV, Net Present Value）。
假設投資的淨現值為正數，代表該投資的結果可以增加企業的價值;反之，如果投資評估的淨現值為負數，代表此投資會減少企業的價值，不應該接受。

>淨現值（NPV）通過計算每個投資期間的成本（負現金流）和收益（正現金流）來確定。期限通常為一年，但可以按季度，半年或數月來衡量。在計算每個時期的現金流量後，每個時期的現值（PV）是通過以定期收益率（市場規定的收益率）貼現其未來價值（見公式）來實現的。

>當然淨現值為正數仍不代表該接受此投資建議，或許存在其他淨現值更高的投資機會。在多項投資案並陳時，應選擇淨現值最高的投資案。淨現值是多數企業進行投資評估時的依據，因為它將投資期間的所有現金流量納入考慮，並且以折現後的金額做計算。

In [74]:
def pv_f(fv,r,n):
    """
    Objective: estimate present value
                     fv
    formula  : pv=-------------
                   (1+r)^n
          fv: fture value
          r : discount periodic rate
          n : number of periods

    Example #1  >>>pv_f(100,0.1,1)
                   90.9090909090909
    
    Example #2: >>>pv_f(r=0.1,fv=100,n=1)
                    90.9090909090909
    """
    return fv/(1+r)**n

#### we just want to write annpv_f() function which applies the preceding equation n times, where n is the number of cash flows. The complete NPV program is given here:

In [75]:
def npv_f(rate, cashflows):
       total = 0.0
       for i in range(0,len(cashflows)):
             total += cashflows[i] / (1 + rate)**i
       return total

# 使用跌代
def npv_f_enumerate(rate, cashflows):
      total = 0.0
      for i, cashflow in enumerate(cashflows):
               total += cashflow / (1 + rate)**i
      return total

In [76]:
r=0.035
cashflows=[-100,-30,10,40,50,45,20]
print(npv_f(r,cashflows))
print(npv_f_enumerate(r,cashflows))

14.158224763725372
14.158224763725372


In [77]:
# for excel
def npv_Excel(rate, cashflows):
       total = 0.0
       for i, cashflow in enumerate(cashflows):
                total += cashflow / (1 + rate)**(i+1)
       return total

r=0.035
cashflows=[-100,-30,10,40,50,45,20]
print(npv_Excel(r,cashflows[1:7])+cashflows[0])

14.158224763725372


In [78]:
# find out which discount rate makes NPV equal zero
cashFlows=(550,-500,-500,-500,1000)
r=0
while(r<1.0):
     r+=0.000001
     npv=npv_f(r,cashFlows)
     if(abs(npv)<=0.0001):
            print(r)

0.07163900000005098
0.33673299999790873


### Data input

In [79]:
#讀取檔案
with open("D:/changelog.txt","r") as f:
    x=f.read()

In [80]:
print(x)

嚜燙plat (Simple Program Launching and Termination)
Copyright (c) 2014-2015 Jody Holmes (Skwire Empire)
http://skwire.dcmembers.com/fp/?page=splat

+ added
* changed
- deleted
! bug fixed

v1.1.8 - 2015-08-10
    + Added ability to create a profile shortcut in your startup folder.
      (Thanks, AtmanActive)
    ! Context menu did not work for reordering profiles.  (Thanks, AtmanActive)

v1.1.7 - 2015-04-15
    + Added a few more wait intervals.

v1.1.6 - 2015-03-28
    ! Reordering entries in a profile wasn't saved when drag and drop was used.
      (Thanks, AtmanActive)

v1.1.5 - 2015-02-11
    + Added "Save log on exit" option.  (Thanks, BGM & Ganamyde)
    + File and folder fields in the Add/Edit dialog now support drag and drop.
      (Thanks, BGM)

v1.1.4 - 2015-02-07
    + Added "Auto-size list columns" option.  (Thanks, miva2)

v1.1.3 - 2015-02-03
    + Added "Notes" column to the Entries list.  (Thanks, BGM)

v1.1.2 - 2015-02-01
    * Changed "Filename" column to "Target".
    !

In [81]:
# 下載ibm歷史資料
# https://finance.yahoo.com/quote/IBM/history?p=IBM
# 放到/data/IBM.csv
import os
import pandas as pd
import pprint
# 設定 data_path
dir_data = './data/'
ibm_data = os.path.join(dir_data, 'IBM.csv')
x = pd.read_csv(ibm_data)
x.head()

Date        Open        High         Low       Close   Adj Close  \
0  2019-03-12  138.520004  139.699997  137.860001  138.279999  132.109131   
1  2019-03-13  138.050003  139.320007  137.850006  138.559998  132.376633   
2  2019-03-14  138.509995  138.940002  138.059998  138.789993  132.596375   
3  2019-03-15  139.369995  140.330002  139.229996  139.429993  133.207825   
4  2019-03-18  139.830002  140.369995  138.720001  140.210007  133.953018   

    Volume  
0  3954700  
1  3173200  
2  2738600  
3  7153700  
4  3268500

In [82]:
# 直接從網頁讀取
url='http://canisius.edu/~yany/data/ibm.csv'
x=pd.read_csv(url)
x.head()

Date      Open      High       Low     Close  Adj Close    Volume
0  1962-01-01  7.713333  7.713333  7.003334  7.226666   2.077531   8760000
1  1962-02-01  7.300000  7.480000  7.093333  7.160000   2.058365   5737600
2  1962-03-01  7.186666  7.413333  7.070000  7.103333   2.042352   5344000
3  1962-04-01  7.100000  7.100000  6.000000  6.053333   1.740458  12851200
4  1962-05-01  6.053333  6.530000  4.733333  5.233333   1.504689  49307200

In [83]:
# 讀取xlsx檔案
xlsx_data = os.path.join(dir_data, 'stockReturns.xlsx')
infile=pd.ExcelFile(xlsx_data)
x=infile.parse(0)
print(x)
print(x.columns)
# 秀出資料欄位的類型與數量
dtype_df = x.dtypes.reset_index()
dtype_df.columns = ["Count", "Column Type"]
dtype_df = dtype_df.groupby("Column Type").aggregate('count').reset_index()
dtype_df

    現金異動代號  現金異動名稱
0  1009023      贖回
1  1009024      申購
2  2001003     經理費
3  2001002     保管費
4  1009034  申購差額退款
5  1009019      匯費
6  1009020     手續費
7  1009016    會計師費
Index(['現金異動代號', '現金異動名稱'], dtype='object')


Column Type  Count
0       int64      1
1      object      1

In [84]:
# load the dataset with an extension of .pkl or .pickle:
# http://www3.canisius.edu/~yany/python/ffMonthly.pkl
import pandas as pd
pkl_data = os.path.join(dir_data, 'ffMonthly.pkl')
x=pd.read_pickle(pkl_data)
x[1:3]


MKT_RF     SMB     HML      RF
192608  0.0264 -0.0140  0.0419  0.0025
192609  0.0036 -0.0132  0.0001  0.0023

In [85]:
# 測試if else
grade=74
if grade>=90:
    print('A')
elif grade >=85:
    print('A-')
elif grade >=80:
    print('B+')
elif grade >=75:
    print('B')
elif grade >=70:
    print('B-')
elif grade>=65:
    print('C+')
else:
    print('D')

B-


In [86]:
# 測試 np array
import numpy as np
a=np.zeros(10)                      # array with 10 zeros 
b=np.zeros((3,2),dtype=float)       # 3 by 2 with zeros 
c=np.ones((4,3),float)              # 4 by 3 with all ones 
d=np.array(range(10),float)         # 0,1, 2,3 .. up to 9 
e1=np.identity(4)                   # identity 4 by 4 matrix 
e2=np.eye(4)                        # same as above 
e3=np.eye(4,k=1)                    # 1 start from k 
f=np.arange(1,20,3,float)           # from 1 to 19 interval 3 
g=np.array([[2,2,2],[3,3,3]])       # 2 by 3 
h=np.zeros_like(g)                  # all zeros 
i=np.ones_like(g)                   # all ones

In [87]:
print(a)
print(b)
print(c)
print(d)
print(e1)
print(e2)
print(e3)
print(f)
print(g)
print(h)
print(i)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
[ 1.  4.  7. 10. 13. 16. 19.]
[[2 2 2]
 [3 3 3]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


#### Matrix manipulation is important when we deal with various matrices:
#### $ C= A+B...(3) $
#### The condition for equation (3) is that matrices A and B should have the same dimensions. For the product of two matrices, we have the following equation:
#### $ C= A*B...(4) $
#### Here,A is an n by k matrix (n rows and k columns), while B is a k by m matrix. Remember that the second dimension of the first matrix should be the same as the first dimension of the second matrix. In this case, it is k. If we assume that the individual data items in C, A, and B are Ci,j (the ith row and the jth column), Ai,j, and Bi,j, we have the following relationship between them:
#### $ C_{i,j} = \sum_{i=1}^{n}\sum_{j=1}^{m}\sum_{p=1}^{k}a_{i,p}b_{p,j}...(5) $

In [88]:
a=np.array([[1,2,3],[4,5,6]],float)    # 2 by 3
b=np.array([[1,2],[3,3],[4,5]],float)  # 3 by 2
np.dot(a,b)                            # 2 by 2
print(np.dot(a,b))

[[19. 23.]
 [43. 53.]]


#### Assume that we have n values of x1, x2, … and xn. There exist two types of means: arithmetic mean and geometric mean; see their genetic definitions here:
#### $ Arithmetic\,mean=  \frac{\sum_{i=1}^{n}x_{i}}{n}...(6)$
#### $ Geometric\,mean=  ((\prod_{i=1}^{n}{x_{i}})^{\frac{1}{n}}...(7)$

In [89]:
# Arithmetic mean
print((2+3+4)/3.)

# Geometric mean
geo_mean=(2*3*4)**(1./3)
print(round(geo_mean,4))

3.0
2.8845


#### For returns, the arithmetic mean's definition remains the same, while the geometric mean of returns is defined differently; see the following equations:
#### $ Arithmetic\,mean=  \frac{\sum_{i=1}^{n}R_{i}}{n}...(8)$
#### $ Geometric\,mean=  [(\prod_{i=1}^{n}({1+R_{i}})]^{\frac{1}{n}}-1...(9)$

In [90]:
import numpy as np
ret=np.array([0.1,0.05,-0.02])
print(np.mean(ret))
print(pow(np.prod(ret+1),1./len(ret))-1)

0.04333333333333334
0.04216388706767926


### Data output

In [91]:
#寫檔
dir_data = './data/'
file_path = os.path.join(dir_data, 'out.txt')
with open(file_path,"w") as f:
    x="This is great"
    f.write(x)

#### 1. Where can you download and install Python?
> for official website
#### 2. Is Python case-sensitive?
> YES
#### 3. How do you assign a set of values to pv in the format of a tuple. Could we change its values after the assignment?
>can't change
><code>
    test_list1 = ('a','b','c')
    test_list2 = ['x','y','z']
    test_tuple = tuple(test_list2)
></code>

#### 4. Estimate the area of a circle if the diameter is 9.7 using Python.

In [106]:
import math
def get_circle_area(raid):
    return math.pi*(raid)**2
# 測試
get_circle_area(9.7)

295.5924527762636

#### 5. How do you assign a value to a new variable?

In [107]:
a = 10
print(a)

10


#### 6. How can you find some sample examples related to Python?
> from google

#### 7.How do you launch Python's help function?

In [ ]:
help()


Welcome to Python 3.7's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.7/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> aaa
No Python documentation found for 'aaa'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.

help> ??print
No Python documentation found for '??print'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.

help> print
Help on built-in function print in mo