### 專案名稱:  TQC+ 人工智慧：機器學習(Python 3)測驗
### 功能描述:  ML00103
### 版權所有: Dunk  
### 程式撰寫: Dunk  
### 撰寫日期：2020/09/30
### 改版日期:  
### 改版備註:  2020/10/15 修改寫法
### 2020/10/16 修改寫法

題號：103 汽車品質預測

難易度：中

（一）、 題目說明：

下載ML00103.zip解壓縮後，請開啟MLD01.py依下列題意進行組合及改寫，再將求取之答案依序輸入填答視窗中。
請注意，資料夾或程式碼中所提供的檔案路徑，不可進行變動。

（二）、 設計說明：

請使用隨機森林分類（Random　Forest　Classifier），撰寫程式，讀取汽車評估資料集cardata.txt，資料集中的前六個屬性為input_data，用來進行對第七個屬性（汽車可接受度）的分類。其取值範圍如下，每一列都包含由逗號分隔的單字清單，請將之解析分割。

欄位名稱	說明
buying	買價	取值範圍是vhigh、 high、 med、 low
maint	維修保養價格	取值範圍是vhigh、 high、 med、 low
doors	門數	取值範圍是2、 3、 4、 5等，5門含5門以上資料表示成5more
persons	載人量	取值範圍是2、 4等，超過4人資料表示成more
lug_boot	行李箱的大小	取值範圍是small、 med、 big
safety	安全	取值範圍是low、 med、 high
car	汽車可接受度	unacc為不可接受，acc為可接受， good為良好，vgood為非常好
請用三折交叉驗證（three-fold cross-validation，將數據分三組，輪換著用其中兩組資料驗證分類器）來計算分類器的準確性。參數設定n_estimators=200, max_depth=8, random_state=7。

input_data = ['high', 'low', '2', 'more', 'med', 'high']（前面六個屬性），依據輸入值預測輸入類別Output class。
請用與前相同之分類器進行"n_estimators"超參數最佳化，參數設定max_depth=8, random_state=7, parameter_grid=np.linspace(25, 200, 8).astype(int)，且改用cv=5。

（三）、 請依序回答下列問題：

請填入分類器的準確度Accuracy of the classifier為多少%（不需填入%，四捨五入計算至小數點後第二位）？

77.66
 此題您答對了，正確答案為：77.66，誤差值為：0.02

input_data = ['high', 'low', '2', 'more', 'med', 'high']（前面六個屬性）。請依據輸入值，填入預測類別的選項？

(A) unacc (B) acc (C) good (D) vgood

B
 此題您答對了，正確答案為：B

請填入"n_estimators"此一超參數的Training scores第一組第一筆數值（計算至小數點第四位後無條件捨去）？

0.9746
 此題您答對了，正確答案為：0.9746，誤差值為：0.0002

請填入"n_estimators"此一超參數的Validation scores最後一組第一筆數值（計算至小數點第四位後無條件捨去）？

0.6676
 此題您答對了，正確答案為：0.6676，誤差值為：0.0002



In [6]:
import numpy as np
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
#import matplotlib.pyplot as plt
#注意匯入
import math
import warnings
warnings.filterwarnings("ignore")

input_file = 'cardata.txt'

df = pd.read_csv(input_file,header = None)
# 注意要複製一份出來
df_source = df.copy(deep=False)
# Reading the data
# X = df.iloc[:,0:df.shape[1]-1]
# y = df.iloc[:,df.shape[1]
# TODO


# Convert string data to numerical data將字串資料轉換為數值資料
# TODO
label_encoder = preprocessing.LabelEncoder()
for name in df.columns:
    # 注意二維陣列
    df_source[name] = label_encoder.fit_transform(df_source[[name]])


# Build a Random Forest classifier建立隨機森林分類器
# TODO
# 注意要名稱為classifier及參數設定
classifier = RandomForestClassifier(n_estimators=200,max_depth=8,random_state=7)
# 注意取值範圍
X = df_source.iloc[:,0:6]
y = df_source.iloc[:,df.shape[1]-1]
classifier.fit(X,y)

# # Cross validation交叉驗證
from sklearn import model_selection
# # TODO
val = model_selection.cross_validate(classifier,X,y,cv=3)


print("Accuracy of the classifier=" + \
      '{0:.2f}'.format(round(val['test_score'].mean()*100,2))       + "%")

# # Testing encoding on single data instance測試單個資料實例上的編碼
input_data = ['high', 'low', '2', 'more', 'med', 'high']
# # TODO
result_data = []
for i in range(len(input_data)):
    # 注意取0
    result_data.append(label_encoder.fit(df.iloc[:,i]).transform([input_data[i]])[0])

y_pred = classifier.predict([result_data])
# car為第六個
namelist = list(label_encoder.fit(df.iloc[:,6]).classes_)
# # Predict and print output for a particular datapoint
# # TODO
print("Output class=",namelist[int(y_pred)])

# ########################
# # Validation curves 驗證曲線
# 注意import
from sklearn.model_selection import validation_curve
# # TODO
parameter_grid = np.linspace(25,200,8).astype(int)

train_scores, validation_scores = validation_curve(classifier, X, y, 
        "n_estimators", parameter_grid, cv=5)
print("##### VALIDATION CURVES #####")
print("\nParam: n_estimators\nTraining scores:\n", train_scores)
print("\nParam: n_estimators\nValidation scores:\n", validation_scores)
# 注意無條件捨去寫法
print("Training scores第一組第一筆數值:",'{:.4f}'.format(\
                                math.floor(train_scores[0][0]*(10**4))/(10**4)))
print("Validation scores最後一組第一筆數值:",'{:.4f}'.format(\
                                math.floor(validation_scores[7][0]*(10**4))/(10**4)))

Accuracy of the classifier=77.66%
Output class= acc
##### VALIDATION CURVES #####

Param: n_estimators
Training scores:
 [[0.97467438 0.97105644 0.97105644 0.97686189 0.96529284]
 [0.97322721 0.97322721 0.97539797 0.98698482 0.96963124]
 [0.97684515 0.97467438 0.97322721 0.98770788 0.98047722]
 [0.97612156 0.97684515 0.97467438 0.98770788 0.97903109]
 [0.97467438 0.97684515 0.97539797 0.98698482 0.98047722]
 [0.97539797 0.97539797 0.97756874 0.98553868 0.97903109]
 [0.97322721 0.97612156 0.97756874 0.98553868 0.97758496]
 [0.97322721 0.97612156 0.97539797 0.98626175 0.97541576]]

Param: n_estimators
Validation scores:
 [[0.66184971 0.78612717 0.79768786 0.8057971  0.88115942]
 [0.67919075 0.80057803 0.78612717 0.7884058  0.89855072]
 [0.65317919 0.79190751 0.78612717 0.78550725 0.90434783]
 [0.63294798 0.79479769 0.76589595 0.7826087  0.91304348]
 [0.66473988 0.77745665 0.79190751 0.79130435 0.90144928]
 [0.70520231 0.77745665 0.79479769 0.79130435 0.90434783]
 [0.65028902 0.7716763  0